version: "3"

services:
  site:
    build: .
    container_name: "leftarchive.ie"
    restart: unless-stopped
    networks:
      - leftarchive-db
    volumes:
      - ./workspace:/var/www/html/workspace
    ports:
      - 127.0.0.1:${PORT}:80
  db:
    image: mariadb:10.11
    container_name: "leftarchive-db"
    networks:
      - leftarchive-db
    volumes:
      - leftarchive-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
volumes:
  leftarchive-db:
networks:
  leftarchive-db:
